networks:
  default:
    name: status
    driver: bridge

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data/uptime-kuma/data:/app/data
    restart: always

  caddy:
    image: caddybuilds/caddy-cloudflare:2.10.0
    environment:
      - VPS_CORE_IP
      - CLOUDFLARE_API_TOKEN
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always
